# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b0af67cd6c949dc31bdfe5970340630"
name = "bogo-mvp"
handle = "bogo-mvp"
application_url = "https://antibodies-pack-lafayette-less.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "primaldad.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://antibodies-pack-lafayette-less.trycloudflare.com/auth/callback",
  "https://antibodies-pack-lafayette-less.trycloudflare.com/auth/shopify/callback",
  "https://antibodies-pack-lafayette-less.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
